match_block_trailing_comma = true
newline_style = "Unix"
use_field_init_shorthand = true
use_small_heuristics = "Max"
use_try_shorthand = true
struct_lit_width = 18

# Turn on once the rustfmt supporting these becomes available on rustup
# width_heuristics = "Max"

# nightly/unstable features
wrap_comments = true
comment_width = 100
format_code_in_doc_comments = true
group_imports = "StdExternalCrate"
imports_granularity = "Module"
imports_layout = "HorizontalVertical"
match_arm_blocks = true
overflow_delimited_expr = true
normalize_comments = true
# too noisy for poise
# struct_lit_single_line = false