//! CommandGroup trait

/// Trait for a struct with a group of commands.
///
/// You should not implement this yourself, but instead use the `poise::group` macro
pub trait CommandGroup<D, E> {
    // /// User data, which is stored and accessible in all command invocations
    // type Data;
    // /// The error type of your commands
    // type Error;
    /// Return a Vec of the `poise::commands` defined in this group
    /// Automatically generated by the macro
    fn commands() -> Vec<crate::Command<D, E>>;
}
